### ISSUE TITLE
Cannot build on Ubuntu 24

### ISSUE THREAD

**Issue by YuriOsokin** [BachiLi/diffvg#93]
I have tried to build on Ubuntu 24.04.1 with Python 3.12, GCC 13.3.0, cmake pip version 3.31.4.
The setup.py script fails during DiffVG compilation on line 66,

```subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)```

 with the following error

```
/home/yuri/workspace/diffvg/pybind11/include/pybind11/cast.h:446:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  446 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +
      |                                    ^~
```

After that there are multiple errors. 

I tried to change the C++ standard to 14 in CMakeLists.txt line 121 `set_property(TARGET diffvg PROPERTY CXX_STANDARD 14)`, because of the warnings, but it did not help.

**Comment by L483** [comment]
I got it going in Ubuntu 24.04 in a Python 3.9 conda environment in a [container from NVIDIA](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda), the specific image is `nvcr.io/nvidia/cuda:12.8.0-cudnn-devel-ubuntu24.04` (also worked on 12.8.1 and 12.9.0). Maybe some of the following `apt-get` installations are not needed (needed them for another tool but can't tell confidently which uses which).

```
# update ubuntu
apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y

# install tools
apt-get install wget -y
apt-get install unzip -y
apt-get install apt-utils -y
apt-get install curl -y
apt-get install cmake build-essential -y
apt-get install git -y

# install conda
cd /tmp || exit
curl -O https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh
bash Anaconda3-2024.10-1-Linux-x86_64.sh -b -p "$HOME"/anaconda
ln -sf "$HOME"/anaconda/bin/* /usr/local/bin
conda -V
conda update conda -y
```

Now clone the repository, and create a conda environment `conda create -n diffvg python=3.9 -y`.

Put the following code block into a script file (e.g. `diffvg-install.sh`) and run `conda run --live-stream -n diffvg bash ./diffvg-install.sh`

```
git submodule update --init --recursive
conda install -y pytorch torchvision -c pytorch
conda install -y numpy
conda install -y scikit-image
conda install -y -c anaconda cmake
conda install -y -c conda-forge ffmpeg
pip install svgwrite
pip install svgpathtools
pip install cssutils
pip install numba
pip install torch-tools
pip install visdom
pip install tensorboard
python setup.py install
```

**Comment by L483** [comment]
I also had some problems to get it going, and I don't know anymore whether I stumbled across the same problem, and if yes, what solved that specific problem.
